### ISSUE TITLE
指定した年月の祝日オブジェクトの読み込み可能とする js を作成し、バンドルした際のファイルサイズを減らす選択が可能となる提案

### ISSUE THREAD

**Issue by camelmasa** [holiday-jp/holiday_jp-js#34]
## 課題

プロジェクトの要件によっては、現在の年月から数年の祝日オブジェクトがあれば要件が満たせる場合があります。
現在、@holiday-jp/holiday_jp npm を利用して webpack などでバンドルした場合 170KB ほどのファイルサイズとなりますが、2022年から2024年までの3年間のみに祝日データを絞った場合 8KB ほどにファイルサイズを低減することが可能となります。

## 改善案

現在 `require('@holiday-jp/holiday_jp')` した際に、自動で1970年から2050年までの祝日オブジェクトを生成しているが、指定した年数の祝日オブジェクトを追加可能とする js を作成するのはどうでしょうか？
既存の js を変更すると破壊的な変更となるので、一旦は以下のように `require('@holiday-jp/holiday_jp/lib/plain')` などの新たな js の作成を提案します。

以下は利用イメージです。
```js
var holiday_jp = require('@holiday-jp/holiday_jp/lib/plain'); // 読み込み時に全ての祝日オブジェクトの読み込みを行わない
var holidays_2022 = require('@holiday-jp/holiday_jp/lib/holidays/2022');
var holidays_2023 = require('@holiday-jp/holiday_jp/lib/holidays/2023');
var holidays_2024 = require('@holiday-jp/holiday_jp/lib/holidays/2024');
holiday_jp.set_holidays([holidays_2022, holidays_2023, holidays_2024])

var holidays = holiday_jp.between(new Date('2022-09-14'), new Date('2022-09-21'));
console.log(holidays[0]['name']); // 敬老の日
```

## その他

雑に上記の実装をしてみたブランチ (https://github.com/camelmasa/holiday_jp-js/commit/87fa14aca374d9fbdb3f4fbee096669ccb2cb77d) を、利用しているプロジェクトでバンドルしたところ以下のような結果となりました。

169.68KB から 7.5KB

<img width="1512" alt="スクリーンショット 2022-06-11 23 49 10" src="https://user-images.githubusercontent.com/189824/173192885-9aa8726c-9a02-48ed-bc77-6d3dbea49555.png">
<img width="1512" alt="スクリーンショット 2022-06-11 23 47 58" src="https://user-images.githubusercontent.com/189824/173192896-e379879e-a89c-47a7-9cc2-d3be9d06bb4c.png">

**Comment by k1LoW** [comment]
サイズを減らすためのアイデア良いと思います。
特にフロントエンドで使用するJavaScriptにおいてはライブラリサイズを減らす方法が選択肢とあるのは良いと思います。

2点だけ気になりました。

1.  holiday_jp は 「[１年毎に誰かがメンテナンスする必要があるのであればgithubとかあるし100年分ぐらいgemの中に持っちゃえばいいじゃん。](https://docs.komagata.org/4860)」というアイデアからはじまっています。今まで通りの全祝日読み込みがデフォルトの挙動（使い方）のままであると良いと思います。
2. 少数の年だけを読む場合は、全祝日を読み込む場合と比べて保持している祝日の期間を超えてしまう場合を特に考慮したほうがよさそうな気がします。2023年までの祝日を読み込んでいるとして「2023年12月28日が祝日でない」と「2024年12月28日の範囲の祝日データセットを読み込んでいない」の2つは区別できる仕組みがあるとよさそうで。

**Comment by camelmasa** [comment]
コメントありがとう

> holiday_jp は 「[１年毎に誰かがメンテナンスする必要があるのであればgithubとかあるし100年分ぐらいgemの中に持っちゃえばいいじゃん。](https://docs.komagata.org/4860)」というアイデアからはじまっています。今まで通りの全祝日読み込みがデフォルトの挙動（使い方）のままであると良いと思います。

**Comment by camelmasa** [comment]
コメントありがとうございます！

> holiday_jp は 「[１年毎に誰かがメンテナンスする必要があるのであればgithubとかあるし100年分ぐらいgemの中に持っちゃえばいいじゃん。](https://docs.komagata.org/4860)」というアイデアからはじまっています。今まで通りの全祝日読み込みがデフォルトの挙動（使い方）のままであると良いと思います。

背景の共有ありがとうございます。こちら理解しました。
現在 package.json の main に指定している js とは別の js を作成して対応することにします。


> 少数の年だけを読む場合は、全祝日を読み込む場合と比べて保持している祝日の期間を超えてしまう場合を特に考慮したほうがよさそうな気がします。2023年までの祝日を読み込んでいるとして「2023年12月28日が祝日でない」と「2024年12月28日の範囲の祝日データセットを読み込んでいない」の2つは区別できる仕組みがあるとよさそうで。

こちらも良いと思います。between, isHoliday 関数実行時、祝日データセットが読み込まれていない範囲だった場合 throw Error するのが良いと思いました。

**Comment by k1LoW** [comment]
良さそうですー

**Comment by camelmasa** [comment]
本業の合間に進めます 🙏

**Comment by camelmasa** [comment]
@k1LoW 

https://github.com/holiday-jp/holiday_jp-js/blob/master/scripts/generate.js

この `scripts` 内のファイルですが、今回の機能追加で変更が必要になりそうなものは、併せて `const` や `let` を使うような最近のコードに変更しようと思います 🙏  問題あれば教えていただければと！

**Comment by k1LoW** [comment]
> 併せて const や let を使うような最近のコードに変更しようと思います 🙏 問題あれば教えていただければと！

ありがとうございます！！！ @camelmasa ++

**Comment by teppeis** [comment]
フロントエンド向けにサイズを抑えるのであれば、データ分割と併せて、データ構造に手を加えるのも効果的だと思います。
現状のデータ構造はかなり冗長なので、サイズ最適化すると以下のような構造のJSONにできます。
手元でやってみるとフルデータでも17KBで、既存の`holidays.js`の204KBに比べて約91%削減されました。ご参考まで。

```json
{
  "defs": {
    "0": {
      "ja": "元日",
      "en": "New Year's Day"
    },
    "1": {
      "ja": "成人の日",
      "en": "Coming of Age Day"
    },
...
  "holidays": {
    "1970-01-01": 0,
    "1970-01-15": 1,
    "1970-02-11": 2,
    "1970-03-21": 3,
...
}
```

**Comment by camelmasa** [comment]
良いアイディアだと思います！マスターとなる YAML を生成する際に同じ構造データが欲しいですね 👀
