### ISSUE TITLE
LISENCEファイルについて

### ISSUE THREAD

**Issue by maxkenkomoda** [holiday-jp/holiday_jp-js#57]
このライブラリを「再配布を伴う利用」するにあたり、ライセンス文を探しています。
もし可能であれば、このリポジトリにライセンスファイルをあげていただきたいです。

参考情報：
このリポジトリ内から参照していると思われる [holiday_jpのプロジェクト](https://github.com/holiday-jp/holiday_jp)にはライセンスファイルを見つけました。

**Comment by k1LoW** [comment]
取り急ぎMITライセンスであることをコメントしておきます。
https://github.com/holiday-jp/holiday_jp-js/blob/f37c88fe90f62af8d2d90bfa74857e39cfed6dd2/package.json#L21

ライセンスファイルも置くようにしておきます

**Comment by maxkenkomoda** [comment]
リプライありがとうございます!

> ライセンスファイルも置くようにしておきます

こちらの都合で非常に申し訳ないのですが、再配布を伴うプロダクトのリリースがあり、
2月6日頃までにライセンス本文をご用意いただけるとありがたいのですが可能でしょうか。。。?
ご検討よろしくお願いいたします🙇‍♂️🙇‍♂️

**Comment by maxkenkomoda** [comment]
お忙しい中ご対応して頂き誠にありがとうございました🙇‍♂️🙇‍♂️
